<?php
declare(strict_types=1);

namespace Tests\Postgres;

use Fyre\DB\ConnectionManager;
use Fyre\DB\Handlers\Postgres\PostgresConnection;

use function getenv;

trait PostgresConnectionTrait
{
    public static function setUpBeforeClass(): void
    {
        ConnectionManager::clear();

        ConnectionManager::setConfig([
            'default' => [
                'className' => PostgresConnection::class,
                'host' => getenv('POSTGRES_HOST'),
                'username' => getenv('POSTGRES_USERNAME'),
                'password' => getenv('POSTGRES_PASSWORD'),
                'database' => getenv('POSTGRES_DATABASE'),
                'port' => getenv('POSTGRES_PORT'),
                'charset' => 'utf8',
                'persist' => true,
            ],
        ]);

        $connection = ConnectionManager::use();

        $connection->query('DROP TABLE IF EXISTS "test"');

        $connection->query(<<<'EOT'
            CREATE TABLE "test" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
                "name" VARCHAR(255) NULL DEFAULT NULL,
                PRIMARY KEY ("id")
            )
        EOT);
    }

    public static function tearDownAfterClass(): void
    {
        $connection = ConnectionManager::use();
        $connection->query('DROP TABLE IF EXISTS "test"');
    }
}
